version: '3'

services:
  app:
    build:
      context: .
    command: "gunicorn --bind 0.0.0.0:5000 app.app:app --access-logfile '-'"
    expose:
      - '5000'
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:latest
    expose:
      - '5432'
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/templates:/static
    depends_on:
      - app

volumes:
  postgres_data: