version: '3'

services:
  app:
    build:
      context: .
    ports:
      - '5000'
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/templates:/app/static
    depends_on:
      - app
